QuizWebApp/Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuizLibrary;

namespace QuizWebApp.Controllers
{
    public class QuizController : Controller
    {
        private static IQuizStorage _quizStorage;

        public QuizController()
        {
            if (_quizStorage == null)
            {
                _quizStorage = new QuizStorageToDatabase();
                //_quizRepo.LoadSampleQuestions();
            }
        }
        // GET: Quiz
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(_quizStorage.GetQuizAll());
        }

        // GET: Quiz/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            return View(_quizStorage.GetQuizById(id));
        }

        // GET: Quiz/Create
        [AllowAnonymous]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Quiz/Create
        [HttpPost]
        public ActionResult Create(Quiz newQuiz, FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                _quizStorage.AddQuiz(newQuiz);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Quiz/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_quizStorage.GetQuizById(id));
        }

        // POST: Quiz/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Quiz quizChanged, FormCollection collection)
        {
            try

            {
                // TODO: Add update logic here
                _quizStorage.EditQuiz(id, quizChanged);
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                return View(_quizStorage.GetQuizById(id));
            }
        }

        // GET: Quiz/Delete/5
        [AllowAnonymous]
        public ActionResult Delete(int id)
        {
            return View(_quizStorage.GetQuizById(id));
        }

        // POST: Quiz/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                _quizStorage.DeleteContent(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

QuizWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <title>@ViewBag.Title - Quiz Game</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/custom.css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div id="navbar-custom" class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Quiz Game App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown" id="nav-dropdown-right">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Quizzes<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Create", "Create", "Quiz")</li>
                            <li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("Take", "Index", "Quiz")</li>
                            <li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("Manage", "Index", "Quiz")</li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Cristian Ventura Apps</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>